version: '3.7'
services: 
    management:
        build: 
            context: .
            dockerfile: ./cmd/management/Dockerfile
        env_file: 
            - "./.env"
        ports:
            - "5000:8080"
        networks: 
            - internal
            - public

networks:
    internal:
        name: ht-internal
        driver: bridge
    public:
        name: ht-public
        driver: bridge