name: Validate pr
on: 
  push:
    paths-ignore: 
    - 'web/**'
    - '.idea/**'
    - '.github/**'
    branches: [ master ]
  pull_request:
    paths-ignore: 
    - 'web/**'
    - '.idea/**'
    - '.github/**'
    types: [opened, synchronize, reopened]

jobs:
  golangci:
    name: Lint golang
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.29
        # Optional: working directory, useful for monorepos
        # working-directory: somedir
        # Optional: golangci-lint command line arguments.
        # args: --issues-exit-code=0
        # Optional: show only new issues if it's a pull request. The default value is `false`.
        # only-new-issues: true
    
  validate-frontend:
    name: Validate frontend
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: eslint
      uses: reviewdog/action-eslint@v1
      with:
        workdir: './web'
        eslint_flags: 'src/'